# Generated by Django 4.2.2 on 2023-06-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaido', '0003_alter_person_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
