# Generated by Django 4.2.2 on 2023-06-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaido', '0005_alter_person_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
